version: "3.9"

networks:
  remindme-nabitu :

services:
  nginx:
    image: nginx:stable-alpine
    container_name: remindme-nabitu-nginx
    ports:
      - "8092:80"
    volumes:
      - ./src:/var/www/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    volumes_from:
      - php
    depends_on:
      - php
      - mysql
    networks:
      - remindme-nabitu
  
  mysql:
    image: mysql:latest
    container_name: remindme-nabitu-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4308:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./config/mysql:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: laravel
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - remindme-nabitu
    mem_limit: 512m

  php:
    image: php:8.2-fpm
    build:
      context: .
      dockerfile: Dockerfile
    container_name: remindme-nabitu-php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9002:9000"
    networks:
      - remindme-nabitu
